const ActionTypes = {
  ADD_ALL_PRODUCTS: "ADD_ALL_PRODUCTS",
  ADD_SELECTED_PRODUCT: "ADD_SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  UPDATE_CART: "UPDATE_CART",
  SET_TOTAL_CART_PRICE: "SET_TOTAL_CART_PRICE",
  DELETE_FROM_CART: "DELETE_FROM_CART",


  UPDATE_CHECKOUT : 'UPDATE_CHECKOUT',
  SET_CHECKOUT_TOTAL:'SET_CHECKOUT_TOTAL',

  BUY_PRODUCT: "BUY_PRODUCT",
  BUY_CART_PRODUCT: "BUY_CART_PRODUCT",
  BUY_ALL_CART_PRODUCTS: "BUY_ALL_CART_PRODUCTS",

  SHOW_MY_ORDERS: "SHOW_MY_ORDERS",
  SET_MY_ORDERS:"SET_MY_ORDERS"
};

export default ActionTypes;
